# Generated by Django 5.0.4 on 2024-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('total_number', models.IntegerField()),
                ('buy_now', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('marka', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField(default=0)),
                ('year', models.SmallIntegerField(max_length=16)),
                ('mileage', models.PositiveIntegerField(max_length=32)),
                ('city', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
                ('with_photo', models.BooleanField()),
                ('color', models.CharField(max_length=30)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6)),
                ('DESCRIPTION', models.TextField()),
            ],
        ),
    ]
